### PR TITLE
Update Fujitsu logo

### PR DESCRIPTION
**Pull request by floreks**

### CODE REVIEW

**Comment by floreks** [comment]
@maciaszczykm could you review please

**Comment by maciaszczykm** [comment]
Favicon seems to have bad quality comparing to `fujitsu.com`:

image

Logo looks good.

**Comment by floreks** [comment]
I've changed it so it looks also good on black background. Original one doesn't look good. Quality is the same, I've removed white pixels.

zrzut ekranu z 2016-06-16 10-15-18

**Comment by maciaszczykm** [comment]
Maybe we should ask UX team to provide favicon which will look good in both scenarios. `fujitsu.com` verrsion is good, but it lacks transparency. 

@cheld Whats your opinion?

**Comment by floreks** [comment]
I'll just update logo for now and stick to original favicon.

**Pull request merged**
