### PR TITLE
Updated colors for fujitsu branding

### PR DESCRIPTION
**Pull request by oxidus**
Slightly different colouring (but looks great now!)

### CODE REVIEW

**Comment by cheld** [comment]
@floreks or @digitalfishpond,  please review

**Comment by floreks** [comment]
Dashboard is following [material design principles](https://www.google.com/design/spec/layout/metrics-keylines.html#metrics-keylines-keylines-spacing). Magic numbers should not be used in the code. We've got variables prepared for that. Instead of this, margin `$baseline-grid / 2` should be used.

Default blue color is set mostly by angular palette. Palette can be overriden in `index_config.js`.

Other colors are defined in `_variables.scss` file. For custom styling we could prepare conditional import/include of our branded file during build or think of something else.

Also it's not good practice to override style by using `zz-foo` directory with style file. SCSS should support conditional imports.

For example we could have variable `$branding-enabled: true;` and then in already existing styles we can add

```css
@include branding-enabled {
    background: red;
  }
```

If this won't work there there are other ways to override current styles.

**Comment by cheld** [comment]
Thanks, zz directory was prepared by @batikanu

Goal was easy rebasing by keeping number of merge conflicts low.

**Comment by fwalker** [comment]
@cheld how to proceed here? @oxidus delivered the input form an UX point of view. Since it seems not trivial, should the technical correct implementation done by the engineering team?

**Comment by cheld** [comment]
I could only quickly check the comment witm my smartphone. Comments about the style like usage of variables baseline by @oxidus. Comments for maintenance by engineering. If it helps rebasing directly. Otherwise with next Branding Iteration. But please discuss

**Comment by cheld** [comment]
refactored and merged

**Pull request closed without merging**
